export class CustomersBillBranch{
    billbranch :  string;
    billBranchId : number;
    customerCode : string;
    billToAddress : string;
    colBr : string;
    colBrId : number;
    submsnBr : string;
    submsnBrId : number;
    pymtTermId : number;
    pymtTermName : string
    contractExpiryDate : string;
    altCollBr : string;
    altCollBrId : number;
    billCtgy : string;
    billToCustName : string;
    billType : string;
    blngCycle : string;
    custMsaId : number;
    gstNumber : string;
    placeOfSupply : string;
    sfxCode : string;
    sfxId : number;
    stateCode :  string;
    billingLevel : string;
    billingLevelCode : string;
    bkgBrId : number;
    bkgBr : string;
    billToAddrId : number;
    billToAddrLine1 : string;
    billToAddrLine2 : string ;
    billToAddrLine3 : string;
    billToLocation : string;
    billToPincode : string;
    ebillFlag : string;
    ebillEmail : string;
    rateCardId : number;
    rateCardCode : string;      
}