import { WmsLines } from './wms-lines.model';

export class WmsBillingSave{
 billDt : string;
 blngBr : string;
 blngBrId : number;
 billToAddr : string;
 collBr : string;
 submsnBr : string;
 pymtTerm : string;
 contractEndDate : Date;
 billId : number;
 billDate : string;
 billFromDt : string;
 billToDt : string;
 billType : string;
 billCtgy : string;
 billPeriod : string;
 custMsaId : number;
 custMsaCode : string;
 billToCustName : string;
 placeOfSupply : string;
 stateCode : string;
 gstNumber : string;
 sfxId : number;
 sfxCode : string;
 blngCycle : string;
 collBrId : number;
 altCollBrId : number;
 altCollBr : string;
 submsnBrId : number;
 baseAmt : number;
 billingLevel : string;
 billingLevelCode : string;
 totalCgstAmt : number;
 totalIgstAmt : number;
 totalSgstAmt : number;
 wmsBIllLines : WmsLines[];
 gstApplied: string;
 billingLevelId : number;
 bkgBrId : number;
 bkgBr : string;
 billToAddrId : number;
 billToAddrLine1 : string;
 billToAddrLine2 : string ;
 billToAddrLine3 : string;
 billToLocation : string;
 billToPincode : string;
 ebillFlag : string;
 billingBrAddress : string;
 billingBrGstNum : string;
 billingBrLocation : string;
 ebillEmail : string;
 rateCardId : number;
 rateCardCode : string;
}