version: '3.1'

services:
  
  # ---------------------------
  # Web Application
  # ---------------------------
  web-application:
    container_name: web-application
    image: nginx
    build:
      context: ../../web-application
      dockerfile: docker/Dockerfile
    volumes:
      - ./dist:/usr/share/nginx/html
    ports:
      - "80:4200"

    networks:
      - frontend

  # -----------------------------
  # Infrastructure Visualization
  # -----------------------------
  scope:
    image: weaveworks/scope:1.1.0
    container_name: weave-scope
    hostname: weave-scope
    pid: "host"
    privileged: true
    ports:
      - "4040:4040"
    expose:
      - "4040"
    labels:
      - "works.weave.role=system"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:rw"
    command:
      - "--probe.docker"
      - "true"
    networks:
      - backend
      