export class AlliedBill {
billtypeId: number;
billType: string;
alliedBillLevel: string;
alliedBillLevelId: number;
prcNonPrc: string;
prcId: string;
documentNumber: string;
waybillNumber: string;
billingLevel: string;
billingLevelId: string;
billingLevelValue: string;
billingBranchId: number;
billingBranch: string;
billingAddress: string;
gstin: string;
submissionBranch: string;
submissionBranchId: number;
collectionBranch: string;
collectionBranchId: number;
billDate: Date;
billPeriodfrom: Date;
billPeriodto: Date;
totaltaxAmount: number;
totalBillAmount: number;
igstAmount: number;
cgstAmount: number;
sgstAmount: number;
baseAmount: number;
billToAddrId : number;
billToAddrLine1 : string;
billToAddrLine2 : string ;
billToAddrLine3 : string;
billToLocation : string;
billToPincode : number;
billToCustName :  string;
gstinRegdFlag : string;
billToCity : string;
billToState : string;
eBillFlag : string;
email : string;
billingBrGstNum : string;
billingBrAddress : string;
billingBrLocation : string;
billingBrCity : string;
billingBrState : string;
billingBrPincode : number;
msaId : number;
msaCode : string;
sfxId : number;
sfxCode : string;
rateCardId : number;
rateCardCode : string;
prcCode : string;
paidToPayStatus : string;
}
