export class BillDetailResponseDto {
    actualoutstandingAmt: number;
    altCollBr: string;
    altCollBrId: number;
    baseAmt: number;
    billCtgy: string;
    billDt: string;
    billId: number;
    billNum: string;
    billToAddr: string;
    billToCustId: number;
    billToCustName: string;
    billType: string;
    bkgBrId: number;
    blngBr: string;
    blngBrId: number;
    blngLevelId: string;
    billingLevelCode: string;
    cgstAmt: number
    collBr: string;
    collBrId: number;
    custAccountId: number;
    custMsaCode: string;
    custMsaId: string;
    custSiteUseId: number;
    gstNum: string;
    igstAmt: number;
    oracleArTrasactionId: string;
    oracleTaxRate: number;
    oracleTaxRateCode: string;
    outstandingAmt: number;
    sfxCode: string;
    sfxId: number;
    sgstAmt: number;
    submsnBr: string;
    submsnBrId: number;
    ttlTaxAmt: number;
    prcId: string;
    prcCode: string;
    billToAddrId : number;
    billToAddrLine1 : string;
    billToAddrLine2 : string ;
    billToAddrLine3 : string;
    billToLocation : string;
    billToPincode : number;
    gstinRegdFlag: string;
    billToCity: string;
    billToState: string;
    ebillFlag: string;
    email: string;
    blngBrGst: string;
    blngBrAddr: string;
    blngBrLocation: string;
    blngBrCity: string;
    blngBrState: string;
    blngBrPincode: number;
    rateCardId: number;
    rateCardCode: string;
    billingLevel:string;
}
