export interface CreditCustomerDetails {
    billingLevel : string;
    billingLevelValue : string;
    billToAddr:string;
    billingByLevel : string;
    billingByLevelId :  string;
    billingByOptionId :  string;
    blngBr : string;
    blngBrId : number;
    collBr : string;
    collBrId : number;
    submsnBr : string;
    submsnBrId : number;
    msaName : string;
    msaId : number;
    gstNum : string;
    gstinRegdFlag : string;
    msaCode : string;
    sfxId : number;
    sfxCode : string;
    rateCardId : number;
    rateCardCode : string;
    email : string;
    eBillFlag : string;
    billToAddrId : number;
    billToAddrLine1 : string;
    billToAddrLine2 : string;
    billToAddrLine3 : string;
    billToLocation : string;
    billToPincode : number;
    billToCity : string;
    billToState : string;
}
